// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosSystem.Model.Context;

#nullable disable

namespace PosSystem.Model.Migrations
{
    [DbContext(typeof(PosSystemContext))]
    [Migration("20251003231436_Migrate-Model-SaleDetail")]
    partial class MigrateModelSaleDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosSystem.Model.Model.Business", b =>
                {
                    b.Property<int>("idBusiness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idBusiness"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("creationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("discount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .IsUnicode(false)
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("owner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("idBusiness");

                    b.HasIndex("phone")
                        .IsUnique();

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Category", b =>
                {
                    b.Property<int>("idCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCategory"));

                    b.Property<DateTime>("creationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("idCategory");

                    b.HasIndex("description")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Product", b =>
                {
                    b.Property<int>("idProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProduct"));

                    b.Property<string>("barcode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("creationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("idCategory")
                        .HasColumnType("int");

                    b.Property<int>("minimumStock")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<decimal>("salePrice")
                        .HasPrecision(18, 2)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("stock")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("idProduct");

                    b.HasIndex("barcode")
                        .IsUnique();

                    b.HasIndex("description")
                        .IsUnique();

                    b.HasIndex("idCategory");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Role", b =>
                {
                    b.Property<int>("idRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRole"));

                    b.Property<DateTime>("creationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("idRole");

                    b.HasIndex("description")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Sale", b =>
                {
                    b.Property<int>("idSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSale"));

                    b.Property<DateOnly?>("annulledDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("bill")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("customer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("discount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .IsUnicode(false)
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<string>("reason")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("saleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("userCancel")
                        .HasColumnType("int");

                    b.HasKey("idSale");

                    b.HasIndex("bill")
                        .IsUnique();

                    b.HasIndex("idUser");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("PosSystem.Model.Model.SaleDetail", b =>
                {
                    b.Property<int>("idSaleDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSaleDetail"));

                    b.Property<int>("count")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("discount")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("idProduct")
                        .HasColumnType("int");

                    b.Property<int>("idSale")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("total")
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idSaleDetail");

                    b.HasIndex("idProduct");

                    b.HasIndex("idSale");

                    b.ToTable("SaleDetail");
                });

            modelBuilder.Entity("PosSystem.Model.Model.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUser"));

                    b.Property<DateTime>("creationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.HasKey("idUser");

                    b.HasIndex("idRole");

                    b.HasIndex("phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Product", b =>
                {
                    b.HasOne("PosSystem.Model.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("idCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Sale", b =>
                {
                    b.HasOne("PosSystem.Model.Model.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PosSystem.Model.Model.SaleDetail", b =>
                {
                    b.HasOne("PosSystem.Model.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("idProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PosSystem.Model.Model.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("idSale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PosSystem.Model.Model.User", b =>
                {
                    b.HasOne("PosSystem.Model.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PosSystem.Model.Model.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("PosSystem.Model.Model.User", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
